ARG ACM_DOCKER_PLATFORM=linux/amd64

FROM --platform=$ACM_DOCKER_PLATFORM rust:1.92-bullseye AS builder
COPY . .
RUN cargo build --release --package ramiel

FROM --platform=$ACM_DOCKER_PLATFORM debian:bullseye-slim

RUN apt-get update; \
    apt-get install -y openssl libxml2 wget libxkbcommon-x11-0 libncurses5 ca-certificates

RUN wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-19/wasi-sdk_19.0_amd64.deb; \
    dpkg -i wasi-sdk_19.0_amd64.deb; \
    rm -f wasi-sdk_19.0_amd64.deb

RUN apt-get purge -y wget; \
    apt-get autoremove -y; \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /target/release/ramiel /usr/local/bin/ramiel
COPY ./wasmtime-cache.toml .

CMD ["ramiel", "--hostname", "0.0.0.0"]
