ARG ACM_DOCKER_PLATFORM=linux/amd64

FROM --platform=$ACM_DOCKER_PLATFORM rust:1.92-bullseye AS builder
COPY . .
RUN cargo build --release --package server

FROM --platform=$ACM_DOCKER_PLATFORM debian:bullseye-slim AS runtime

RUN apt-get update; \
    apt-get install -y openssl ca-certificates; \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /target/release/server /usr/local/bin/server

CMD ["server", "--hostname", "0.0.0.0"]
