#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

TEST_MODE=${ACM_DEPLOY_TEST_MODE:-0}
case "$TEST_MODE" in 0|1) ;; *) printf '%s\n' 'acm-deploy: ACM_DEPLOY_TEST_MODE must be 0 or 1' >&2; exit 1 ;; esac
if [ "$TEST_MODE" = 0 ]; then for v in ACM_DEPLOY_REPO_ROOT ACM_DEPLOY_COMPOSE_FILE ACM_DEPLOY_ENV_FILE ACM_DEPLOY_STATE_DIR ACM_DEPLOY_LOCK_PATH ACM_DEPLOY_DOCKER_BIN ACM_DEPLOY_FLOCK_BIN ACM_DEPLOY_DATA_DIR ACM_DEPLOY_WAIT_TIMEOUT; do [ -z "${!v+x}" ] || { printf 'acm-deploy: %s override requires ACM_DEPLOY_TEST_MODE=1\n' "$v" >&2; exit 1; }; done; fi
effective_uid(){ if [ "$TEST_MODE" = 1 ]; then printf '%s\n' "${ACM_DEPLOY_TEST_EUID:-0}"; else id -u; fi; }
require_root(){ [ "$DRY_RUN" = 1 ] || [ "$(effective_uid)" = 0 ] || die 'mutating lifecycle commands require effective UID 0'; }

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
repository_arg=''; DRY_RUN=0
while [ $# -gt 0 ]; do
  case "$1" in
    --repository-dir) [ -z "$repository_arg" ] && [ $# -gt 1 ] && [ -n "${2:-}" ] || { printf '%s\n' 'acm-deploy: --repository-dir requires one absolute path' >&2; exit 2; }; repository_arg=$2; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    *) break ;;
  esac
done

die(){ printf 'acm-deploy: %s\n' "$*" >&2; exit 1; }
now(){ date -u +%Y-%m-%dT%H:%M:%SZ; }
usage(){ printf '%s\n' "Usage: $0 [--repository-dir ABSOLUTE_PATH] [--dry-run] initial <revision> | deploy <revision> --backup DIR | rollback <revision> --backup DIR | rollback-start --backup DIR | acknowledge-state | validate | build | up | smoke | status" 'The installed runner requires --repository-dir. acknowledge-state archives a non-completed state and records an operator acknowledgment; it never deletes state.'; }
assert_repository_path(){ local path=$1 part current=/; [[ "$path" =~ ^/[A-Za-z0-9._/-]+$ ]] && [[ "$path" != *//* && "$path" != */./* && "$path" != */../* && "$path" != */. && "$path" != */.. && "$path" != */ ]] || die '--repository-dir must be a normalized absolute literal path'; IFS=/ read -r -a parts <<< "${path#/}"; for part in "${parts[@]}"; do [ -z "$part" ] && continue; current="${current%/}/$part"; [ ! -L "$current" ] || die "repository path must not contain symlink components: $current"; done; }
is_checkout(){ [ -d "$1" ] && [ ! -L "$1" ] && git -C "$1" rev-parse --is-inside-work-tree >/dev/null 2>&1; }
if [ -n "$repository_arg" ]; then assert_repository_path "$repository_arg"; REPO_ROOT=$repository_arg
elif [ "$TEST_MODE" = 1 ] && [ -n "${ACM_DEPLOY_REPO_ROOT:-}" ]; then REPO_ROOT=$ACM_DEPLOY_REPO_ROOT
else candidate=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd -P); [ "$SCRIPT_DIR" = "$candidate/deploy" ] || die '--repository-dir is required when the runner is outside an ACM checkout'; REPO_ROOT=$candidate
fi
COMPOSE_FILE=${ACM_DEPLOY_COMPOSE_FILE:-$REPO_ROOT/compose.production.yml}; ENV_FILE=${ACM_DEPLOY_ENV_FILE:-$REPO_ROOT/deploy/.env.production}
STATE_DIR=${ACM_DEPLOY_STATE_DIR:-$REPO_ROOT/.local/deploy}; STATE_FILE=$STATE_DIR/production-state.env
LOCK_PATH=${ACM_DEPLOY_LOCK_PATH:-/run/acm/acm-operation.lock}; DOCKER_BIN=${ACM_DEPLOY_DOCKER_BIN:-docker}; FLOCK_BIN=${ACM_DEPLOY_FLOCK_BIN:-flock}; WAIT_TIMEOUT=${ACM_DEPLOY_WAIT_TIMEOUT:-180}
DB_HELPER=$SCRIPT_DIR/acm-db.sh; SMOKE_HELPER=$SCRIPT_DIR/smoke.sh
lock_held=0; state_initialized=0; exit_handling=0; rollback_start_bypass=0
state_action='' state_prior='' state_target='' state_backup='' state_backup_revision='' state_backup_migration='' state_target_migration='' state_phase='' state_failed='' state_started='' state_updated='' state_completed='' state_status='' state_exit=''

run(){ if [ "$DRY_RUN" = 1 ]; then printf '+ '; printf '%q ' "$@"; printf '\n'; else "$@"; fi; }
compose(){ run "$DOCKER_BIN" compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"; }
file_mode(){ stat -c '%a' "$1" 2>/dev/null || stat -f '%Lp' "$1"; }
file_uid(){ stat -c '%u' "$1" 2>/dev/null || stat -f '%u' "$1"; }
file_gid(){ stat -c '%g' "$1" 2>/dev/null || stat -f '%g' "$1"; }
assert_secure_dir(){ local p=$1 label=$2 mode uid gid; [ -d "$p" ] && [ ! -L "$p" ] || die "unsafe $label: $p"; mode=$(file_mode "$p"); [ $((8#$mode & 0022)) -eq 0 ] || die "$label must not be group- or world-writable: $p"; if [ "$TEST_MODE" = 0 ]; then uid=$(file_uid "$p"); gid=$(file_gid "$p"); [ "$uid" = 0 ] && [ "$gid" = 0 ] || die "$label must be owned by root:root: $p"; fi; }
assert_secure_file(){ local p=$1 label=$2 mode uid gid; [ -f "$p" ] && [ ! -L "$p" ] || die "unsafe $label: $p"; mode=$(file_mode "$p"); [ $((8#$mode & 0022)) -eq 0 ] || die "$label must not be group- or world-writable: $p"; if [ "$TEST_MODE" = 0 ]; then uid=$(file_uid "$p"); gid=$(file_gid "$p"); [ "$uid" = 0 ] && [ "$gid" = 0 ] || die "$label must be owned by root:root: $p"; fi; }
validate_migration_files(){ local p; while IFS= read -r -d '' p; do [ ! -L "$p" ] || die "unsafe migration path: $p"; if [ -f "$p" ]; then assert_secure_file "$p" 'migration file'; elif [ -d "$p" ]; then assert_secure_dir "$p" 'migration directory'; else die "unsafe migration path: $p"; fi; done < <(find -P "$REPO_ROOT/migrations" -print0); }
validate_checkout_path(){ local rel=$1 current=$REPO_ROOT part; [[ "$rel" != /* && "$rel" != *'//' && "$rel" != *'/./'* && "$rel" != *'/../'* && "$rel" != . && "$rel" != .. && "$rel" != */ ]] || die "unsafe tracked path: $rel"; IFS=/ read -r -a parts <<< "$rel"; for part in "${parts[@]}"; do [ -n "$part" ] || die "unsafe tracked path: $rel"; current="$current/$part"; if [ "$current" = "$REPO_ROOT/$rel" ]; then [ ! -L "$current" ] || die "unsafe tracked path: $rel"; [ -f "$current" ] || [ -d "$current" ] || die "unsafe tracked path: $rel"; if [ -f "$current" ]; then assert_secure_file "$current" 'tracked file'; else assert_secure_dir "$current" 'tracked directory'; fi; else assert_secure_dir "$current" 'tracked path ancestor'; fi; done; }
operational_path(){ case "$1" in deploy|deploy/.env.production|.local|.local/deploy|.local/deploy/*) return 0;; *) return 1;; esac; }
validate_tracked_checkout(){ local rel p; while IFS= read -r -d '' rel; do validate_checkout_path "$rel"; done < <(git -C "$REPO_ROOT" ls-files -z); while IFS= read -r -d '' p; do rel=${p#"$REPO_ROOT/"}; [ "$p" = "$REPO_ROOT" ] && continue; operational_path "$rel" && continue; if [ -d "$p" ] && [ ! -L "$p" ] && git -C "$REPO_ROOT" ls-files --error-unmatch -- "$rel" >/dev/null 2>&1; then continue; fi; git -C "$REPO_ROOT" ls-files --error-unmatch -- "$rel" >/dev/null 2>&1 && continue; die "nontracked checkout entry is not allowed: $rel"; done < <(find -P "$REPO_ROOT" -path "$REPO_ROOT/.git" -prune -o -mindepth 1 -print0); }
validate_production_checkout(){ local part current=/; local -a parts; assert_repository_path "$REPO_ROOT"; IFS=/ read -r -a parts <<< "${REPO_ROOT#/}"; assert_secure_dir / 'repository ancestor'; for part in "${parts[@]}"; do [ -z "$part" ] && continue; current="${current%/}/$part"; assert_secure_dir "$current" 'repository ancestor'; done; assert_secure_dir "$REPO_ROOT/.git" 'Git directory'; is_checkout "$REPO_ROOT" || die 'repository root is not a valid Git checkout'; validate_tracked_checkout; assert_secure_file "$COMPOSE_FILE" 'compose file'; assert_secure_file "$ENV_FILE" 'environment file'; [ "$(file_mode "$ENV_FILE")" = 600 ] || die 'environment file must be mode 0600'; validate_migration_files; }
preflight(){ validate_production_checkout; [ -f "$COMPOSE_FILE" ] && [ ! -L "$COMPOSE_FILE" ] || die 'missing or unsafe compose.production.yml'; [ -f "$ENV_FILE" ] && [ ! -L "$ENV_FILE" ] || die 'missing or unsafe deploy/.env.production'; local m d; m=$(file_mode "$ENV_FILE"); [ "$m" = 600 ] || die 'environment file must be mode 0600'; [[ "$WAIT_TIMEOUT" =~ ^[1-9][0-9]*$ ]] || die 'wait timeout must be a positive integer'; d=$(data_dir); assert_data_dir "$d"; }
require_clean(){ [ -z "$(git -C "$REPO_ROOT" status --porcelain --untracked-files=all -- . ':(exclude)deploy/.env.production' ':(exclude).local/deploy/**')" ] || die 'operation requires a clean checkout'; }
commit(){ git -C "$REPO_ROOT" rev-parse --verify --quiet "$1^{commit}" 2>/dev/null || die "revision is not an existing commit: $1"; }
current(){ git -C "$REPO_ROOT" rev-parse --verify HEAD; }
hash_stdin(){ if command -v sha256sum >/dev/null 2>&1; then sha256sum | cut -d ' ' -f1; elif command -v shasum >/dev/null 2>&1; then shasum -a 256 | cut -d ' ' -f1; else die 'SHA-256 tool unavailable'; fi; }
migration_identity_current(){ validate_migration_files; (cd "$REPO_ROOT"; while IFS= read -r f; do printf '%s\0' "$f"; cat -- "$f"; printf '\0'; done < <(find -P migrations -type f -print | LC_ALL=C sort)) | hash_stdin; }
migration_identity_commit(){ git -C "$REPO_ROOT" ls-tree -r --name-only "$1" -- migrations | LC_ALL=C sort | while IFS= read -r f; do [ -n "$f" ] || continue; printf '%s\0' "$f"; git -C "$REPO_ROOT" show "$1:$f"; printf '\0'; done | hash_stdin; }
data_dir(){ local l v='' found=0; if [ "$TEST_MODE" = 1 ] && [ -n "${ACM_DEPLOY_DATA_DIR+x}" ]; then v=$ACM_DEPLOY_DATA_DIR; found=1; else while IFS= read -r l || [ -n "$l" ]; do l=${l%$'\r'}; case "$l" in ACM_DATA_DIR=*) [ "$found" = 0 ] || die 'duplicate ACM_DATA_DIR in environment file'; v=${l#ACM_DATA_DIR=}; found=1 ;; esac; done < "$ENV_FILE"; fi; [ "$found" = 1 ] || die 'ACM_DATA_DIR is missing from environment file'; case "$v" in \"*) [ "${#v}" -ge 2 ] && [ "${v: -1}" = '"' ] || die 'malformed quoted ACM_DATA_DIR in environment file'; v=${v:1:${#v}-2};; \') die 'malformed quoted ACM_DATA_DIR in environment file';; \'*) [ "${#v}" -ge 2 ] && [ "${v: -1}" = "'" ] || die 'malformed quoted ACM_DATA_DIR in environment file'; v=${v:1:${#v}-2};; *\"*|*\'*) die 'malformed quoted ACM_DATA_DIR in environment file';; esac; [[ "$v" =~ ^/[A-Za-z0-9._/-]+$ ]] && [[ "$v" != *//* && "$v" != */./* && "$v" != */../* && "$v" != */. && "$v" != */.. && "$v" != */ ]] || die 'ACM_DATA_DIR must be a normalized absolute literal path'; printf '%s\n' "$v"; }
assert_data_dir(){ local p=$1 current mode uid gid; current=$(dirname -- "$p"); while :; do assert_secure_dir "$current" 'data directory ancestor'; [ "$current" = / ] && break; current=$(dirname -- "$current"); done; [ -d "$p" ] && [ ! -L "$p" ] || die "data directory must be a real non-symlink directory: $p"; mode=$(file_mode "$p"); [ "$mode" = 750 ] || die "data directory must be mode 0750: $p"; if [ "$TEST_MODE" = 0 ]; then uid=$(file_uid "$p"); gid=$(file_gid "$p"); [ "$uid" = 10001 ] && [ "$gid" = 10001 ] || die "data directory must be owned by 10001:10001: $p"; fi; }
assert_no_db(){ local d path; d=$(data_dir); for path in "$d/db.sqlite" "$d/db.sqlite-wal" "$d/db.sqlite-shm" "$d/db.sqlite-journal" "$d"/db.sqlite-*; do [ ! -e "$path" ] && [ ! -L "$path" ] || die 'initial refuses existing production SQLite files'; done; }
require_stable_helpers(){ [ -x "$DB_HELPER" ] && [ ! -L "$DB_HELPER" ] && grep -Fq -- '--repository-dir' "$DB_HELPER" || die 'stable acm-db helper is unavailable or incompatible'; [ -x "$SMOKE_HELPER" ] && [ ! -L "$SMOKE_HELPER" ] || die 'stable smoke helper is unavailable'; }
lock(){ if [ "$DRY_RUN" = 1 ]; then return 0; fi; command -v "$FLOCK_BIN" >/dev/null 2>&1 || die 'flock is required'; local d=${LOCK_PATH%/*} mode uid; if [ "$TEST_MODE" = 0 ]; then assert_secure_dir /run 'lock path ancestor'; fi; if [ ! -e "$d" ] && [ ! -L "$d" ]; then mkdir -m 0700 -- "$d" || { [ -d "$d" ] && [ ! -L "$d" ] || die 'could not create operation lock directory'; }; fi; [ -d "$d" ] && [ ! -L "$d" ] || die 'operation lock directory must be a non-symlink directory'; mode=$(file_mode "$d"); [ "$mode" = 700 ] || die 'operation lock directory must be mode 0700'; if [ "$TEST_MODE" = 0 ]; then uid=$(file_uid "$d"); [ "$uid" = 0 ] || die 'operation lock directory must be root-owned'; fi; if [ ! -e "$LOCK_PATH" ] && [ ! -L "$LOCK_PATH" ]; then (umask 077; set -C; : > "$LOCK_PATH") 2>/dev/null || { [ -f "$LOCK_PATH" ] && [ ! -L "$LOCK_PATH" ] || die 'could not create operation lock'; }; fi; [ -f "$LOCK_PATH" ] && [ ! -L "$LOCK_PATH" ] || die 'operation lock must be a regular non-symlink file'; mode=$(file_mode "$LOCK_PATH"); [ "$mode" = 600 ] || die 'operation lock must be mode 0600'; if [ "$TEST_MODE" = 0 ]; then uid=$(file_uid "$LOCK_PATH"); [ "$uid" = 0 ] || die 'operation lock must be root-owned'; fi; exec 9<>"$LOCK_PATH" || die 'could not open operation lock'; "$FLOCK_BIN" -n 9 || die 'another ACM operation is active'; lock_held=1; trap operation_exit EXIT; trap 'exit 130' INT; trap 'exit 143' TERM; }
unlock(){ if [ "$lock_held" != 1 ]; then return 0; fi; "$FLOCK_BIN" -u 9 2>/dev/null || true; exec 9>&- || true; lock_held=0; }
assert_private_dir(){ assert_secure_dir "$1" "$2"; [ "$(file_mode "$1")" = 700 ] || die "$2 must be mode 0700: $1"; }
assert_private_file(){ assert_secure_file "$1" "$2"; [ "$(file_mode "$1")" = 600 ] || die "$2 must be mode 0600: $1"; }
create_private_dir(){ local p=$1 label=$2; if [ ! -e "$p" ] && [ ! -L "$p" ]; then (umask 077; mkdir -m 0700 -- "$p") || die "could not create $label: $p"; fi; assert_private_dir "$p" "$label"; }
validate_state_path(){ local create=${1:-0}; if [ "$STATE_DIR" = "$REPO_ROOT/.local/deploy" ]; then if [ "$create" = 1 ]; then create_private_dir "$REPO_ROOT/.local" 'state parent directory'; create_private_dir "$STATE_DIR" 'deployment state directory'; else assert_private_dir "$REPO_ROOT/.local" 'state parent directory'; assert_private_dir "$STATE_DIR" 'deployment state directory'; fi; elif [ "$create" = 1 ]; then create_private_dir "$STATE_DIR" 'deployment state directory'; else assert_private_dir "$STATE_DIR" 'deployment state directory'; fi; if [ -e "$STATE_FILE" ] || [ -L "$STATE_FILE" ]; then assert_private_file "$STATE_FILE" 'deployment state file'; fi; }
write_state(){ if [ "$DRY_RUN" = 1 ]; then return 0; fi; validate_state_path 1; local t=$STATE_DIR/.production-state.$$.${RANDOM}.tmp; (umask 077; set -C; printf 'action=%s\nprior_revision=%s\ntarget_revision=%s\nbackup_dir=%s\nbackup_source_revision=%s\nbackup_migration_identity=%s\ntarget_migration_identity=%s\nphase=%s\nfailed_phase=%s\nstarted_at=%s\nupdated_at=%s\ncompleted_at=%s\nstatus=%s\nlast_exit_status=%s\n' "$state_action" "$state_prior" "$state_target" "$state_backup" "$state_backup_revision" "$state_backup_migration" "$state_target_migration" "$state_phase" "$state_failed" "$state_started" "$state_updated" "$state_completed" "$state_status" "$state_exit" > "$t") || die 'could not create deployment state temporary file'; assert_private_file "$t" 'deployment state temporary file'; mv -f -- "$t" "$STATE_FILE"; assert_private_file "$STATE_FILE" 'deployment state file'; }
state_phase(){ state_phase=$1; state_status=$2; state_updated=$(now); write_state; }
operation_exit(){ local s=$?; [ "$exit_handling" = 0 ] || return; exit_handling=1; trap - EXIT INT TERM; if [ "$s" -ne 0 ] && [ "$state_initialized" = 1 ] && [ "$DRY_RUN" = 0 ]; then state_failed=$state_phase; state_phase=failed; state_status=failed; state_exit=$s; state_updated=$(now); write_state || true; fi; unlock; exit "$s"; }
read_state(){ [ ! -L "$STATE_DIR" ] && [ -d "$STATE_DIR" ] || die 'deployment state is missing'; validate_state_path; [ -f "$STATE_FILE" ] && [ ! -L "$STATE_FILE" ] || die 'deployment state is missing'; local l k v seen=' '; state_action='' state_prior='' state_target='' state_backup='' state_backup_revision='' state_backup_migration='' state_target_migration='' state_phase='' state_failed='' state_started='' state_updated='' state_completed='' state_status='' state_exit=''; while IFS= read -r l || [ -n "$l" ]; do case "$l" in *=*) k=${l%%=*}; v=${l#*=} ;; *) die 'invalid deployment state' ;; esac; [[ "$seen" != *" $k "* ]] || die "duplicate deployment state field: $k"; seen+="$k "; case "$k" in action)state_action=$v;;prior_revision)state_prior=$v;;target_revision)state_target=$v;;backup_dir)state_backup=$v;;backup_source_revision)state_backup_revision=$v;;backup_migration_identity)state_backup_migration=$v;;target_migration_identity)state_target_migration=$v;;phase)state_phase=$v;;failed_phase)state_failed=$v;;started_at)state_started=$v;;updated_at)state_updated=$v;;completed_at)state_completed=$v;;status)state_status=$v;;last_exit_status)state_exit=$v;;*)die "invalid deployment state field: $k";;esac; done < "$STATE_FILE"; for k in action prior_revision target_revision backup_dir backup_source_revision backup_migration_identity target_migration_identity phase failed_phase started_at updated_at completed_at status last_exit_status; do [[ "$seen" == *" $k "* ]] || die "missing deployment state field: $k"; done; [[ "$state_action" =~ ^(initial|deploy|rollback)$ && "$state_prior" =~ ^[0-9a-f]{40}$ && "$state_target" =~ ^[0-9a-f]{40}$ && "$state_target_migration" =~ ^[0-9a-f]{64}$ && "$state_phase" =~ ^(checkout_pending|checkout_complete|build_pending|build_complete|up_pending|up_complete|smoke_pending|smoke_complete|rollback_prepared|complete|failed|acknowledged)$ && "$state_status" =~ ^(running|prepared|completed|failed|acknowledged)$ && "$state_exit" =~ ^[0-9]+$ ]] || die 'deployment state has invalid values'; }
assert_state_overwritable(){ [ ! -e "$STATE_FILE" ] || { read_state; [ "$state_status" = completed ] || [ "$state_status" = acknowledged ] || die 'existing deployment state is not completed; run acknowledge-state after reviewing it'; }; }
acknowledge_state(){ [ $# = 0 ] || die 'acknowledge-state accepts no arguments'; require_root; lock; validate_production_checkout; read_state; [ "$state_status" != completed ] && [ "$state_status" != acknowledged ] || die 'deployment state does not require acknowledgment'; [ "$DRY_RUN" = 1 ] && { printf 'would archive and acknowledge %s\n' "$STATE_FILE"; return; }; local archive stamp; stamp=$(date -u +%Y%m%dT%H%M%SZ); archive=$STATE_DIR/production-state.${stamp}.$$.ack.env; [ ! -e "$archive" ] && [ ! -L "$archive" ] || die 'deployment state archive already exists'; ln "$STATE_FILE" "$archive" || die 'could not archive deployment state'; assert_private_file "$archive" 'deployment state archive'; state_phase=acknowledged; state_status=acknowledged; state_updated=$(now); write_state; printf 'state acknowledged; preserved evidence at %s\n' "$archive"; trap - EXIT INT TERM; unlock; }
canonical_backup(){ [ -d "$1" ] && [ ! -L "$1" ] || die 'backup directory is missing or unsafe'; (CDPATH= cd -- "$1" && pwd -P); }
backup_metadata(){ local b out l k v seen=' ' src='' mig=''; b=$(canonical_backup "$1"); require_stable_helpers; out=$("$DB_HELPER" --repository-dir "$REPO_ROOT" metadata --backup-dir "$b") || die 'backup metadata verification failed'; while IFS= read -r l || [ -n "$l" ]; do case "$l" in BACKUP_DIR=*)k=BACKUP_DIR;v=${l#*=};;SOURCE_REVISION=*)k=SOURCE_REVISION;v=${l#*=};;MIGRATION_IDENTITY=*)k=MIGRATION_IDENTITY;v=${l#*=};;*)die 'invalid backup metadata output';;esac; [[ "$seen" != *" $k "* ]] || die 'duplicate backup metadata field'; seen+="$k "; case "$k" in BACKUP_DIR)[ "$v" = "$b" ] || die 'backup metadata path is not canonical';;SOURCE_REVISION)src=$v;;MIGRATION_IDENTITY)mig=$v;;esac; done <<< "$out"; [[ "$seen" == *' BACKUP_DIR '* && "$src" =~ ^[0-9a-f]{40}$ && "$mig" =~ ^[0-9a-f]{64}$ ]] || die 'incomplete backup metadata'; BACKUP_DIR=$b BACKUP_SOURCE=$src BACKUP_MIGRATION=$mig; }
assert_backup_for_current(){ backup_metadata "$1"; [ "$BACKUP_SOURCE" = "$(current)" ] || die 'backup source revision is not the current checkout'; [ "$BACKUP_MIGRATION" = "$(migration_identity_current)" ] || die 'backup migration identity is not the current checkout'; }
validate(){ preflight; compose config --quiet; }; build(){ require_root; validate; compose build; }; up(){ require_root; validate_production_checkout; if [ -f "$STATE_FILE" ]; then read_state; [ "$state_action" != rollback ] || [ "$state_status" = completed ] || [ "$rollback_start_bypass" = 1 ] || die 'up refuses an incomplete rollback state; use rollback-start'; fi; validate; compose up -d --wait --wait-timeout "$WAIT_TIMEOUT"; }; rollback_start_up(){ rollback_start_bypass=1; up; rollback_start_bypass=0; }; status(){ preflight; compose ps; }; smoke(){ validate; require_stable_helpers; run "$SMOKE_HELPER" --repository-dir "$REPO_ROOT"; }; checkout(){ [ "$(current)" = "$1" ] || run git -C "$REPO_ROOT" checkout --detach "$1"; validate_production_checkout; }
start_state(){ state_action=$1;state_prior=$2;state_target=$3;state_backup=${4:-};state_backup_revision=${5:-};state_backup_migration=${6:-};state_target_migration=${7:-};state_phase=checkout_pending;state_failed='';state_started=$(now);state_updated=$state_started;state_completed='';state_status=running;state_exit=0;state_initialized=1;write_state; }
phase(){ local pending=$1 command=$2 complete=$3; shift 3; state_phase "$pending" running; "$command" "$@"; state_phase "$complete" running; }
finish(){ state_phase complete completed; state_completed=$state_updated; state_exit=0; write_state; state_initialized=0; trap - EXIT INT TERM; unlock; }
standalone_mutation(){ require_root; lock; "$@"; trap - EXIT INT TERM; unlock; }
initial(){ [ $# = 1 ] || die 'usage: initial <revision>'; require_root; lock; preflight; require_clean; { [ ! -e "$STATE_FILE" ] && [ ! -L "$STATE_FILE" ]; } || die 'initial requires no deployment state'; local t p i; t=$(commit "$1");p=$(current);i=$(migration_identity_commit "$t");assert_no_db;start_state initial "$p" "$t" '' '' '' "$i";phase checkout_pending checkout checkout_complete "$t";phase build_pending build build_complete;phase up_pending up up_complete;phase smoke_pending smoke smoke_complete;finish; }
deploy(){ [ $# = 2 ] || die 'usage: deploy <revision> --backup DIR'; require_root; lock; preflight;require_clean;assert_state_overwritable;local t p i;t=$(commit "$1");p=$(current);assert_backup_for_current "$2";i=$(migration_identity_commit "$t");start_state deploy "$p" "$t" "$BACKUP_DIR" "$BACKUP_SOURCE" "$BACKUP_MIGRATION" "$i";phase checkout_pending checkout checkout_complete "$t";phase build_pending build build_complete;phase up_pending up up_complete;phase smoke_pending smoke smoke_complete;finish; }
rollback(){ [ $# = 2 ] || die 'usage: rollback <revision> --backup DIR'; require_root; lock;preflight;require_clean;assert_state_overwritable;require_stable_helpers;local t p i;t=$(commit "$1");p=$(current);i=$(migration_identity_commit "$t");backup_metadata "$2";[ "$BACKUP_SOURCE" = "$t" ] || die 'rollback backup source revision does not match target';[ "$BACKUP_MIGRATION" = "$i" ] || die 'rollback backup migration identity does not match target';start_state rollback "$p" "$t" "$BACKUP_DIR" "$BACKUP_SOURCE" "$BACKUP_MIGRATION" "$i";phase checkout_pending checkout checkout_complete "$t";phase build_pending build build_complete;state_phase rollback_prepared prepared;state_initialized=0;trap - EXIT INT TERM;unlock; }
rollback_start(){ [ $# = 1 ] || die 'usage: rollback-start --backup DIR'; require_root; lock;validate_production_checkout;read_state;[ "$state_action" = rollback ] && [ "$state_phase" = rollback_prepared ] && [ "$state_status" = prepared ] || die 'rollback-start requires strict rollback_prepared state';preflight;require_clean;[ "$(current)" = "$state_target" ] && [ "$(migration_identity_current)" = "$state_target_migration" ] || die 'current checkout does not match rollback state';backup_metadata "$1";[ "$BACKUP_DIR" = "$state_backup" ] && [ "$BACKUP_SOURCE" = "$state_backup_revision" ] && [ "$BACKUP_MIGRATION" = "$state_backup_migration" ] && [ "$BACKUP_SOURCE" = "$state_target" ] && [ "$BACKUP_MIGRATION" = "$state_target_migration" ] || die 'backup metadata does not exactly match rollback state';state_initialized=1;phase up_pending rollback_start_up up_complete;phase smoke_pending smoke smoke_complete;finish; }
main(){ case "${1:-}" in initial)shift;initial "$@";;deploy)shift;[ $# = 3 ]&&[ "$2" = --backup ]||die 'usage: deploy <revision> --backup DIR';deploy "$1" "$3";;rollback)shift;[ $# = 3 ]&&[ "$2" = --backup ]||die 'usage: rollback <revision> --backup DIR';rollback "$1" "$3";;rollback-start)shift;[ $# = 2 ]&&[ "$1" = --backup ]||die 'usage: rollback-start --backup DIR';rollback_start "$2";;acknowledge-state)shift;acknowledge_state "$@";;build|up)[ $# = 1 ]||die "$1 accepts no arguments";standalone_mutation "$1";;validate|status|smoke)[ $# = 1 ]||die "$1 accepts no arguments";"$1";;-h|--help|help)usage;;*)usage >&2;exit 2;;esac; }
main "$@"
