name: Build Docker containers

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [server, ramiel]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build Docker image
        run: >-
          docker build --platform linux/amd64 --provenance=false
          --file Dockerfile.${{ matrix.component }}
          --tag acm-${{ matrix.component }}:ci .
